name: Chautauqua Ridge Farm
description:
  - ADGA Purebred and American Nubian Goats
  - AKC Anatolian Shepherds
url: http://www.chqridge.com
avatar:

collections:
  goats:
    output: true
    permalink: /goats/:path/
  anatolianshepherds:
    output: true
    permalink: /anatolianshepherds/:path/

footer-links:
  dribbble:
  email: jamie@chqridge.com
  facebook:
  flickr: 126812864@N04
  github:
  instagram:
  linkedin:
  pinterest:
  rss: # just type anything here for a working RSS icon, make sure you set the "url" above!
  twitter:
  stackoverflow:

disqus:
google_analytics: UA-53578820-1

baseurl: ""
exclude:
  - CNAME
  - LICENSE
  - README.md
  - Gemfile
  - Gemfile.lock
markdown: kramdown
highlighter: pygments
permalink: /:title

sass:
  sass_dir: _scss
  style: :compressed

gems:
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
